[package]
name = "tagged"
version = "0.1.1"
authors = ["Sam Rijs <srijs@airpost.net>"]
description = "PhantomData's partner in crime!"
documentation = "http://srijs.github.io/rust-tagged/tagged"
repository = "https://github.com/srijs/rust-tagged"
license = "MIT/Apache-2.0"
